######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 27 21:51:06 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pbar.h
FORMS += pbar.ui
SOURCES += main.cpp pbar.cpp
